version: '3'

services:
  openldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: "My Organization"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    ports:
      - "389:389"
      - "636:636"
    networks:
      - my-network

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mychatpassword
      MYSQL_DATABASE: mychat
      MYSQL_USER: mychat
      MYSQL_PASSWORD: mychatpassword
    ports:
      - "3306:3306"
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: mychat
      PMA_PASSWORD: mychatpassword
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - my-network

networks:
  my-network:
